config/routes.rb
Rails.application.routes.draw do

  get "inquiry" => "inquiry#index"
  post "inquiry/confirm" => "inquiry#confirm"
  post "inquiry/thanks" => "inquiry#thanks"

  get 'menus/show'

  root to: 'toppages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
  
  attr_accessor :inquiry_type, :first_name, :name, :first_name_kana, :name_kana, :email, :phone_number,:message 
  
  validates :inquiry_type, :presence => {:message => 'お問い合わせ項目を選択してください'}
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'お問い合わせ内容を入力してください'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    # 入力画面を表示
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    # 入力値のチェック
    @inquiry = Inquiry.new(inquiry_params)
    if @inquiry.valid?
      # OK。確認画面を表示
      render :action => 'confirm'
    else
      # NG。入力画面を再表示
      render :action => 'index'
    end
  end

  def thanks
    # メール送信
    @inquiry = Inquiry.new(inquiry_params)
    InquiryMailer.received_email(@inquiry).deliver

    # 完了画面を表示
    render :action => 'thanks'
  end

  private
  def inquiry_params
    params.require(:inquiry).permit(:inquiry_type, :first_name, :name, :first_name_kana, :name_kana, :email, :phone_number, :message)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def show
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiry_helper.rb
module InquiryHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/inquiry/confirm.html.erb
<div class="newWrap">
  <div class="newTitle">
    <h3>ご入力内容確認</h3>
  </div>
  <div class="newContent">
    <%= form_for @inquiry, :url => inquiry_thanks_path do |f| %>
    <div class="row">
      <div class="form-group">
        <div class="col-md-4">お問い合わせ項目</div>
        <div class="col-md-8"><%= f.hidden_field :inquiry_type %><%= @inquiry.inquiry_type %></div>
      </div>
      
      <div class="form-group">
        <div class="col-md-4">お名前</div>
        <div class="col-md-4"><%= f.hidden_field :first_name %><%= @inquiry.first_name %></div>
        <div class="col-md-4"><%= f.hidden_field :name %><%= @inquiry.name %></div>
        <div class="col-md-4 col-md-offset-4"><%= f.hidden_field :first_name_kana %><%= @inquiry.first_name_kana %></div>
        <div class="col-md-4"><%= f.hidden_field :name_kana %><%= @inquiry.name_kana %></div>
      </div>
      
      <div class="form-group">
        <div class="col-md-4">メールアドレス</div>
        <div class="col-md-8"><%= f.hidden_field :email %><%= @inquiry.email %></div>
      </div>
      
      <div class="form-group">
        <div class="col-md-4">電話番号</div>
        <div class="col-md-8"><%= f.hidden_field :phone_number %><%= @inquiry.phone_number %></div>
      </div>
      
      <div class="form-group">
        <div class="col-md-4">お問い合わせ内容</div>
        <div class="col-md-8"><%= f.hidden_field :message %><%= simple_format(@inquiry.message) %></div>
      </div>
    </div>
      
      <%= f.submit '送信する', class: 'btn btn-block btn-success' %>
    <% end %>
  </div>
</div>

app/views/inquiry/index.html.erb
<% @page_title = 'お問い合わせ' %>
<div class="newWrap">
  <div class="newTitle">
    <h3>CONTACT</h3>
    <div>お問い合わせ</div>
  </div>
  <div class="newContent">
    <%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
      <% if @inquiry.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @inquiry.errors.each do |attr, msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="row">
          <div class="form-group">
          <div class="col-md-4">
            <div class="contact-title">お問い合わせ項目<span class="text-danger">*</span>
            </div>
          </div>
          <div class="col-md-8">
            <%= f.select :inquiry_type,["ご予約に関するお問い合わせ","その他お問い合わせ"] %>
          </div>
        </div>
        
        <div class="form-group">
          
          <div class="col-md-4">
            <div class="contact-title">お名前<span class="text-danger">*</span></div>
          </div>
          
          <div class="col-md-4"><%= f.text_field :first_name, :placeholder => "姓",class: 'form-control mb-2' %></div>
          <div class="col-md-4"><%= f.text_field :name, :placeholder => "名",class: 'form-control mb-2' %></div>
          
          <div class="col-md-4 col-md-offset-4">
            <div class="text-margin">
              <%= f.text_field :first_name_kana, :placeholder => "セイ", class: 'form-control mb-2' %>
            </div>
          </div>
          
          <div class="col-md-4">
            <div class="text-margin">
              <%= f.text_field :name_kana, :placeholder => "メイ",class: 'form-control mb-2' %>
            </div>
          </div>
        </div>
        
        <div class="form-group">
          <div class="col-md-4">
            <div class="contact-title">メールアドレス<span class="text-danger">*</span>
            </div>
          </div>
          <div class="col-md-8"><%= f.text_field :email, :placeholder => "core@color.com",class: 'form-control mb-2' %></div>
        </div>
        
        <div class="form-group">
          
          <div class="col-md-4">
            <div class="contact-title">電話番号</div>
          </div>
          <div class="col-md-8"><%= f.text_field :phone_number, :placeholder => "000-1234-5678",class: 'form-control mb-2' %></div>
        </div>
        
        <div class="form-group">
          <div class="col-md-4">
            <div class="contact-title">お問い合わせ内容<span class="text-danger">*</span>
            </div>
          </div>
          <div class="col-md-8"><%= f.text_area :message, :placeholder => "お問い合わせ内容をご入力ください",class: 'form-control mb-2', rows: '6' %></div>
        </div>
      </div>
      <%= f.submit '確認', class: 'btn btn-block btn-success' %>
    <% end %>
  </div>
</div>

app/views/inquiry/thanks.html.erb
<div class="newWrap">
  <div class="thanks-message">
    <div class="alert alert-success" role="alert"><strong>送信しました</strong>
    ：　お問い合わせありがとうございます。</div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <section id="main">
    <h1><img src="/images/icon.jpeg" alt="Core color">Core color</h1>
  
    <div class="sns">
      <ul>
        <li>
          <%= link_to "https://www.facebook.com/Core-Color-1873699249419673/?modal=admin_todo_tour", :target=>["_blank"] do %>
            <%= fa_icon("facebook-square 2x")%>
          <% end %>
        </li>
        <li>
          <%= link_to "https://www.instagram.com/core_color/?hl=ja", :target=>["_blank"] do %>
            <%= fa_icon("instagram 2x")%>
          <% end %>
        </li>
      </ul>
    </div>
  </section>
  
    <nav class="navbar">
        <span class="col-md-2"><%=link_to "TOP", root_path(anchor: "top") %></span>
        <span class="col-md-2"><%=link_to "ABOUT", root_path(anchor: "about") %></span>
        <span class="col-md-2"><%=link_to "MENU", root_path(anchor: "menu") %></span>
        <span class="col-md-2"><%=link_to "NEWS", root_path(anchor: "news") %></span>
        <span class="col-md-2"><%=link_to "ACCESS", root_path(anchor: "access") %></span>
        <span class="col-md-2"><%=link_to "CONTACT", inquiry_path %></span>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Corecolor</title>
    <%= csrf_meta_tags %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="container">
      <div class="row">
        <%= render "layouts/navbar" %>
      
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/menus/show.html.erb
<section id="menu1">
  <div class="menu">
    <div class="h2">
      <h2>TCカラーセラピー</h2>
    </div>
    <div class="col-md-5 col-md-offset-1">
      <img class="menu-image" src="/images/tc.jpeg">
    </div>
    
    <div class="col-md-6">
      <div class="menu-description">
        カラーセラピーとは占いではなく色彩療法です。<br>
        色にはそれぞれキーワード（意味）が存在します。<br>
        セラピーは14本のカラーボトルから選んで頂き、<br>
        選んだボトルの色から今の心の状態を紐解きます。<br>
        人は表に出ている部分が顕在意識として全体の1〜2割を占め、<br>
        残りの8〜9割は心の奥底に潜んでいる潜在意識とされています。<br>
        セラピーではこの潜在意識に気づいて自分と向き合い、<br>
        理解して整理し、前向きになることを目的としています。<br>
        不思議なことに好きな色を選ばないかもしれません。<br>
        それは今のあなたの潜在意識が選んでいるからです。
      </div>
    </div>
    
    <div class="price">
      <h4>Price: ¥3,000(40分)</h4> 
      <span>延長10分につき¥500</span>
    </div>
    <div class="contact_btn">
      <%= link_to inquiry_path, class: "square_btn" do%>
        ご予約はこちら
      <% end %>
    </div>
  </div>
</section>

<section id="menu2">
  <div class="menu">
    <h2>Sci/ART<br>パーソナルカラー診断</h2>
    
    <div class="col-md-5 col-md-offset-1">
      <img class="menu-image" src="/images/sciart.jpg">
    </div>
    
    <div class="col-md-6">
      <div class="menu-description">
        Sci/ART(サイアート)・パーソナルカラーとは・・・<br>
        ニューヨーク、ボストン、フロリダを中心とした全米から全米へと<br>
        飛躍を続けるSci/ART社の12分類カラー診断システムです。<br>
        肌の色や52枚のドレープ(布)を使い診断していきます。<br>
        この診断を受ければ自分に似合う色、似合わない色を知ることができ、<br>
        着こなしの幅も広がり洋服を選ぶ時間も短縮できます。<br>
        自分ににある色を着こなすことで、第一印象もよくなり、<br>
        若々しくなり、自分に自信を持って自分らしくいられるでしょう。
      </div>
    </div>
    
    <div class="price">
      <h4>Price: ¥6,000(約90分)</h4> 
      <span>延長10分につき¥500</span>
      <p>・2名様での受講の場合1人¥5,000になります</p>
    </div>
    <div class="contact_btn">
      <%= link_to inquiry_path, class: "square_btn" do%>
        ご予約はこちら
      <% end %>
    </div>
  </div>
</section>

<section id="menu3">
  <div class="menu">
    <h2>TCカラーセラピスト講座</h2>
    
    <div class="col-md-5 col-md-offset-1">
      <img class="menu-image" src="/images/therapist.jpeg">
    </div>
    
    <div class="col-md-6">
       <div class="menu-description">
        1日5時間の講習で簡単にリーディングができるように開発された<br>
        解説書と14本のボトル付きの講座です。
      </div>
    </div>
   
    <div class="price">
      <h4>Price: ¥19,000</h4>
    </div>
    
    <div class="contact_btn">
      <%= link_to inquiry_path, class: "square_btn" do%>
        ご予約はこちら
      <% end %>
    </div>
  </div>
</section>

<!--<section id="menu4">-->
<!--  <div class="menu">-->
<!--      <h2>色育講座</h2>-->
<!--    <div class="col-md-5 col-md-offset-1">-->
<!--      <img class="menu-image" src="/images/iroiku.jpg">-->
<!--    </div>-->
    
<!--    <div class="col-md-6">-->
<!--      <div class="menu-description">-->
<!--        色育(いろいく)とは・・・<br>-->
<!--        現代の大人も子供も足りないと言われている3つの力<br>-->
<!--        (想像力・集中力・コミュニケーション力)を誰の身近にもある色を<br>-->
<!--        通して楽しみながら育むことを目的としています。<br>-->
<!--        「色育」では色で分析や決めつけたりはしません。<br>-->
<!--        「待つ」「受け入れる」「寄り添う」ことを大切にしています。<br>-->
<!--        人にはそれぞれの色(個性)があります。<br>-->
<!--        自分と他人の色を比べるのではなく、お互いの色を尊重することをゴールにしています。-->
<!--      </div>-->
<!--    </div>-->
    
<!--    <div class="price">-->
<!--      <h4>---</h4>-->
<!--      <span>---</span>-->
<!--      <p>--- ---</p>-->
<!--    </div>-->
<!--    <div class="contact_btn">-->
<!--      <%= link_to inquiry_path, class: "square_btn" do%>-->
<!--        ご予約はこちら-->
<!--      <% end %>-->
<!--    </div>-->
<!--  </div>-->
<!--</section>-->

<footer>
  <small>&copy; 2018 Core Color</small>
</footer>

app/views/toppages/index.html.erb
<!--<div id="carousel" class="carousel-slide" data-ride="carousel">-->
<!--	<ol class="carousel-indicators">-->
<!--		<li class="active" data-target="#carousel" data-slide-to="0"></li>-->
<!--		<li data-target="#carousel" data-slide-to="1"></li>-->
<!--		<li data-target="#carousel" data-slide-to="2"></li>-->
<!--	</ol>-->
<!--	<div class="carousel-inner" role="listbox">-->
<!--		<div class="item active">-->
<!--			<img src="images/slide1.jpeg" alt="First slide">-->
<!--		</div>-->
<!--		<div class="item">-->
<!--			<img src="images/slide2.jpeg" alt="Second slide">-->
<!--		</div>-->
<!--		<div class="item">-->
<!--			<img src="../img/sampleC-1140x500.png" alt="Third slide">-->
<!--		</div>-->
<!--	</div>-->
<!--</div>-->


<section>
  <div id="about" class="section-inner">
      <h2>ABOUT</h2>
      <h3>What's Color Therapy?</h3>
      <p class="description">
        カラーセラピーとは占いではなく、色彩療法です。<br>
        色にはそれぞれキーワード（意味）が存在します。<br>
        人は表に出ている部分が顕在意識として全体の1〜2割を占めており、<br>
        残りの8〜9割は心の奥底に潜んでいる潜在意識とされています。<br>
        セラピーではこの潜在意識に気づいて自分と向き合い、<br>
        理解して整理し、前向きになることを目的としています。<br>
      </p>
    </div>
    
    <h3>講師</h3>
    <div class="col-md-5 col-md-offset-1 ">
      <img src="images/teacher1.jpeg">
    </div>
    <div class="col-md-6">
      <div class="name">
        <div>石山　美咲</div>
        <p>Misaki Ishiyama</p>
      </div>
      
      <div class="description">
        <div>TCマスターカラーセラピスト</div>
        <div>Sci/ARTパーソナルカラーアナリスト</div>
        <div>色育アドバイザー</div>
        <p>
            私たちの生活から切り離せない色の大切さを知り、<br>
          それを多くの方に知ってもらうために自宅にてサロンを開業しました。<br>
          現在はTCマスターカラーセラピストとして皆様の心を整理するお手伝いをしています。
          また、Sci/ARTパーソナルカラーアナリストとしてその人に似合う色を見つけ、
          TCカラーセラピストを育てる講座も行なっています。<br>
        </p>
      </div>
    </div>
  </div>
</section>

<section id="menu" class="clearfix">
  <div class="section-inner">
    <h2>LESSON MENU</h2>
    
    <div class="menu-image">
      <div class="col-md-3">
        <img src="images/tc.jpeg">
        <%= link_to "TC color", menus_show_path(anchor: "menu1"), class: "square_btn" %>
      </div>
    </div>
    
    <div class="menu-image">
      <div class="col-md-3">
        <img src="images/sciart.jpg">
        <%= link_to "Sci/ART", menus_show_path(anchor: "menu2"), class: "square_btn" %>
      </div>
    </div>
    
    <div class="menu-image">
      <div class="col-md-3">
        <img src="images/therapist.jpeg">
        <%= link_to "Therapist", menus_show_path(anchor: "menu3"), class: "square_btn" %>
      </div>
    </div>
    
    <div class="menu-image">
      <div class="col-md-3">
        <img src="images/iroiku.jpg">
        <%= link_to "Iroiku", menus_show_path(anchor: "menu4"), class: "square_btn" %>
      </div>
    </div>
  </div>
</section>

<section id="news">
  <div class="section-inner">
    <h2>NEWS</h2>
    <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FCore-Color-1873699249419673%2F%3Fmodal%3Dadmin_todo_tour&tabs=timeline&width=500&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId"
      width="500" height="500" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
  </div>
</section>

<section id="access">
  <div class="section-inner">
    <h2>ACCESS</h2>
      <div class="map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3692.8775494378397!2d139.72060285664332!3d35.53063192586685!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x601860d014b357d5%3A0xc3e0f9b1dd95b653!2z44CSMjEwLTA4MDQg56We5aWI5bed55yM5bed5bSO5biC5bed5bSO5Yy66Jek5bSO77yR5LiB55uu77yS77yYIOODtOOCp-ODs-ODh-ODn-OCog!5e0!3m2!1sja!2sjp!4v1544721222787" 
        width="1000" height="450" frameborder="0" style="border:0" allowfullscreen>
        </iframe>
      </div>
    </div>  
    
    <p>
      〒210-0804 神奈川県川崎市川崎区藤崎1-28-13<br>
      ・京急線「川崎大師駅」より徒歩5分<br>
      ・JR川崎駅よりバス（川02,03,04,05,07）10分。<br>
      「藤崎一丁目」下車、徒歩1分。<br>
      ※ご希望のレッスン日時やその他お問い合わせにつきましては<br>
      下記お問い合わせフォームよりご連絡下さい。
    </p>
  </div>
</section>

<div class="clear"></div>

<section id="contact">
  <div class="section-inner">
    <%= link_to inquiry_path, class: "square_btn" do %>
      <h3>CONTACT</h3>
      <p>ご予約・お問い合わせはこちらから</p>
    <% end %>
  </div>
</section>

<footer>
  <small>&copy; 2018 Core Color</small>
</footer>